### ISSUE TITLE
Sign in service

### ISSUE THREAD

**Issue by jgotorbl** [psiebert1899/tcm#17]
The user can sign in just by typing the email correctly. No matter which password types in, he gets logged in. Besides, the first time he logs in the profile data panel shows up, but if he logs out and then he logs back in that same page does not appear onto the screen.

**Comment by jgotorbl** [comment]
Solved the part in which the data profile panel shows up. When the user logs in, the onInit function of the  class checks that the user property of the user service is not null or undefined. When the user logged out, that variable was not set back to null or undefined, so if the user logged back in the data panel did not show

**Comment by psiebert1899** [comment]
Closed by @jgotorbl with 84015bf683fe37d2e8a16520fa259d679f6b0c7e
