### ISSUE TITLE
Employee List - Searching

### ISSUE THREAD

**Issue by psiebert1899** [psiebert1899/tcm#19]
Set up a search field using two way data binding that allows for searching of the employee list. Search By fields should include name, department, division, skills, title and potentially more

**Comment by psiebert1899** [comment]
Check into two way data binding and filters. The Employee List component holds an array of all employees with relevant data.

**Comment by psiebert1899** [comment]
Form field for searches needs styled, user should be able to select the field they are searching against, currently it only uses name.

**Comment by jgotorbl** [comment]
Style added to search. Need to find a solution so the user is able to search by field

**Comment by jgotorbl** [comment]
https://silviomoreto.github.io/bootstrap-select/examples/ for styling the field selector

Possible links for multiple argument pipe implementation
http://stackoverflow.com/questions/36423903/angular2-pipe-for-multiple-arguments
http://stackoverflow.com/questions/36816788/how-do-i-call-an-angular-2-pipe-with-multiple-arguments

**Comment by psiebert1899** [comment]
Closed By Jaime
